config/routes.rb
Rails.application.routes.draw do
  get 'user_comment_rating/rateit'

  devise_for :users
  resources :ratings
  resources :tags
  resources :comments
  resources :topics
  resources :posts

  
 root 'topics#index'
   
   
   resources :topics do
       resources :posts
     end

	  resources :posts do
       resources :comments
    end
  resources :posts do
    resources :ratings
  end

  post 'posts/update_post'
  post 'posts/alert'
  match '/user' => "posts#user" ,via: :get
  get 'comments/:id/rate' => 'comments#rate', as: :rate
  patch 'comments/:id/rating' => 'comments#rating', as: :commentrating
  patch 'posts/:id/rating' => 'posts#rating', as: :postrating
  get 'topics/device' => 'topics#', as: :device

  devise_scope :user do
    match '/sign-in' => "devise/sessions#new", :as => :login ,via: :get
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  has_many :user_comment_ratings
  has_many :users, through: :user_comment_ratings
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource :except => [:rate,:rating]
  # GET /comments
  # GET /comments.json
  def index
    @post = Post.find(params[:post_id])
    @comment = @post.comments
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new

  end

  # GET /comments/1/edit
  def edit
	@comment = Comment.find(params[:id])
  end

  # POST /comments
  # POST /comments.json
  def create
    @post = Post.find(params[:post_id])
  	@comment = @post.comments.build(comment_params)
    @comment.update(:name => current_user.email)
    @comment.update(:user_id => current_user.id)
    respond_to do |format|
      if @comment.save
        format.html { redirect_to post_url(@post), notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
        format.js # render comments/create.js.erb
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def rate
    @comment=Comment.find(params[:id])
  end

  def rating
    @comment=Comment.find(params[:id])
    ucr=UserCommentRating.new(:rating => params[:rate_comment])
    ucr.save
    @comment.user_comment_ratings<<ucr
    current_user.user_comment_ratings<<ucr
    respond_to do |format|
      format.html {redirect_to rate_path(@comment)}
    end
  end
  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
	@comment = Comment.find(params[:id])
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to post_url(@comment.post_id), notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
	@comment = Comment.find(params[:id])
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to post_url(@comment.post_id), notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:name, :comment, :post,:user_id,:rate_comment)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<br>
<%= comment.name %> <strong> : </strong> <%= comment.comment %>  <% if comment.user_id == current_user.id%> <%= link_to "Edit",edit_comment_path(comment)%> | <%= link_to 'Delete', comment, method: :delete, data: { confirm: 'Are you sure?' } %><%end%> | <%= link_to "<button>Rate</button>".html_safe, rate_path(comment)%><br>

app/views/comments/_form.html.erb
<%= form_for [@post,@comment] do |f| %>
    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
    <div id="txt-field">
      <%= f.label :comment %><br>
      <%= f.text_area :comment %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/comments/create.js.erb
$('#comments').append("<%= j render @comment %>");
$('#ct').val("")

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>
<center>
<style>
table, th, td {
    border: 1px solid black;
    border-collapse: collapse;
	
}
th, td {
    padding: 5px;
text-align: center;
}
</style>
<h1><%= @post.name %></h1>

<table style='width:75%'>
  <thead>
    <tr>
      <th>Name</th>
      <th>Author</th>
      <th>Comment</th>

      <th colspan="3">Edit_options</th>
    </tr>
  </thead>

  <tbody>
    <% @comment.each do |comment| %>
      <tr>
        <td><%= comment.name %></td>
        <td><%= User.find_by(:id => @post.user_id).email %></td>
        <td><%= comment.comment %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_post_comment_path %> |
<%= link_to 'Back to Posts', post_path(@post) %>
</center>

app/views/comments/rate.html.erb
<h1>Post Message : <%=@comment.post.message%></h1>
<br><h2><%=@comment.name%>  :  "<%=@comment.comment%>"</h2>
<br><h3>Rate it</h3>
<%= form_for(@comment,:url=>commentrating_path(@comment)) do |f|%>
    <div id="radio_buttons">
      <% (1..5).each do |ratings|%>
          <%=radio_button_tag "rate_comment",ratings%><%=ratings%>
      <%end%>
      <%= f.submit('rate')%>
    </div>
<%end%>
<br>
<h3>Previous Ratings</h3>

<% if @comment.user_comment_ratings.any?%>
    <table>
      <thead><th>User</th><th>Rating</th></thead><tbody>
        <%@comment.user_comment_ratings.each do|a|%>
          <tr><td><%=User.find_by_id(a.user_id).email%></td><td><%=a.rating%></td></tr>
        <%end%>
        </tbody></table>
<%else%>
        Not Yet Rated
<%end%>
<br>
  <strong><%= link_to "Back",post_path(@comment.post)%></strong>