config/routes.rb
Rails.application.routes.draw do
  get 'user_comment_rating/rateit'

  devise_for :users
  resources :ratings
  resources :tags
  resources :comments
  resources :topics
  resources :posts

  
 root 'topics#index'
   
   
   resources :topics do
       resources :posts
     end

	  resources :posts do
       resources :comments
    end
  resources :posts do
    resources :ratings
  end

  post 'posts/update_post'
  post 'posts/alert'
  match '/user' => "posts#user" ,via: :get
  get 'comments/:id/rate' => 'comments#rate', as: :rate
  patch 'comments/:id/rating' => 'comments#rating', as: :commentrating
  patch 'posts/:id/rating' => 'posts#rating', as: :postrating
  get 'topics/device' => 'topics#', as: :device

  devise_scope :user do
    match '/sign-in' => "devise/sessions#new", :as => :login ,via: :get
  end

end

app/models/topic.rb
class Topic < ActiveRecord::Base
	has_many :posts


end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]
  #skip_before_action :authenticate_user!
  #load_and_authorize_resource
  # GET /topics
  # GET /topics.json
  def index
    @topics = Topic.all
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
	  @topic = Topic.find(params[:id])

      end

	# GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
    @topic = Topic.find(params[:id])
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(topic_params)
    respond_to do |format|
      if @topic.save
        format.html { redirect_to @topic, notice: 'Topic was successfully created.' }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
	  @topic = Topic.find(params[:id])
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic = Topic.find(params[:id])
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to topics_url, notice: 'Topic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def device
    if browser.android?
      redirect_to 'https://www.play.google.com'
    elsif browser.ios?
      redirect_to 'https://itunes.apple.com'
    else
      redirect_to 'https://google.co.in'

    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      params.require(:topic).permit(:name)
    end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<%= form_for(@topic) do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% @topic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/topics/edit.html.erb
<h1>Editing Topic</h1>

<%= render 'form' %>

<%= link_to 'Show', @topic %> |
<%= link_to 'Back', topics_path %>

app/views/topics/index.html.erb
	<p id="notice"><%= notice %></p>
	<style>
table, th, td {
    border: 1px solid black;
    border-collapse: collapse;
	
}
th, td {
    padding: 5px;
text-align: center;
}
</style>
<center>
<h1>Listing Topics</h1>

<table style = 'width:75%' >
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3">Edit</th>
    </tr>
  </thead>
<ol>
  <tbody>
    <% @topics.each do |topic| %>
      <tr>
        <td><%= topic.name %></td>
        <td><%= link_to 'Show', topic_posts_path(topic) %></td>
        <td><%= link_to 'Edit', edit_topic_path(topic) %></td>
        <td><%= link_to 'Destroy', topic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
  </ol>
</table>

<br>
<%= link_to 'New Topic', new_topic_path %>|
<%= link_to 'All Posts',posts_path %>

app/views/topics/new.html.erb
<h1>New Topic</h1>

<%= render 'form' %>

<%= link_to 'Back', topics_path %>

app/views/topics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @topic.name %>
</p>
<%= link_to 'Posts', topic_posts_path(@topic) %> |
<%= link_to 'Edit', edit_topic_path(@topic) %> |
<%= link_to 'Back', topics_path %>