config/routes.rb
Rails.application.routes.draw do
  get 'user_comment_rating/rateit'

  devise_for :users
  resources :ratings
  resources :tags
  resources :comments
  resources :topics
  resources :posts

  
 root 'topics#index'
   
   
   resources :topics do
       resources :posts
     end

	  resources :posts do
       resources :comments
    end
  resources :posts do
    resources :ratings
  end

  post 'posts/update_post'
  post 'posts/alert'
  match '/user' => "posts#user" ,via: :get
  get 'comments/:id/rate' => 'comments#rate', as: :rate
  patch 'comments/:id/rating' => 'comments#rating', as: :commentrating
  patch 'posts/:id/rating' => 'posts#rating', as: :postrating
  get 'topics/device' => 'topics#', as: :device

  devise_scope :user do
    match '/sign-in' => "devise/sessions#new", :as => :login ,via: :get
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :topic
  has_many :comments
  has_many :ratings
  belongs_to :user

  #scope :recent, -> {where :user_id = 3)}

  scope :t , ->(from) { where("posts.created_at > ?", from) }
  scope :f , ->(from) { where("posts.created_at < ?", from) }
  #scope :created_before, ->(time) { where("created_at < ?", time) }

  has_and_belongs_to_many :users , join_table: :posts_users_read_status
  has_and_belongs_to_many :tags

  has_attached_file :image


  validates_presence_of :name, :presence => true,message: "Name should not be blank"
  validates_length_of :name,:maximum => 20,message: "Maximum 20 characters are allowed"
  validates_attachment :image,
                       content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] },
                       size:         { less_than: 1.megabytes }, message:"upload image less than 1MB"


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController



  before_action :set_post, only: [:show, :edit, :update, :destroy,:update_post]

  load_and_authorize_resource :except => [:user,:rating,:date_filter]

  skip_before_action :authenticate_user! ,only: [:user]

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, :notice =>" Hey "+ exception.message
  end


  # GET /posts
  # GET /posts.json
  def index

    if  params[:from_date].present?
     from=params[:from_date]
     to=params[:to_date]

    else
      from =Date.yesterday
      to =Date.today
    end
	if (params[:topic_id]).present?
    @topic = Topic.find(params[:topic_id])
	  @posts = @topic.posts.paginate(page: params[:page], per_page: 10)
    @tags = Tag.all
    @post = @topic.posts.new
	else
	  #@posts = Post.eager_load(:topic,:user).paginate(page: params[:page], per_page: 10)
    @posts=Post.t(from).f(to).eager_load(:topic,:user).paginate(page: params[:page], per_page: 10)

  end
  end

  def user
    authenticate_or_request_with_http_basic do |username, password|
      @person = User.find_by_email(username)
      if @person.valid_password?(password)
        render json: @person
      else
        render json:{error: "access denied"}
      end
    end

  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comments = @post.comments

  end

  def update_post
      @post.users<<(current_user)
  end

  # GET /posts/new
  def new
      @topic = Topic.find(params[:topic_id])
      @tags=Tag.all
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
    @tags=Tag.all
  end

  # POST /posts
  # POST /posts.json
  def create

	  @topic = Topic.find(params[:topic_id])
    @posts = @topic.posts.new(post_params)
    @posts.update(:user_id => current_user.id)


    respond_to do |format|

        format.html { redirect_to topic_posts_path(@topic) }
        format.json { render :show, status: :created, location: @posts }
        format.js

    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    @post = Post.find(params[:id])
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_path(@post), notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end



  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to topic_posts_path(@post.topic), notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  def rating
   puts "hello"
    @post=Post.find(params[:id])
    @post.ratings.create(:star =>params[:rate])
   puts "hiiii"
    respond_to do |format|
    format.html { redirect_to post_path(@post), notice: 'Thanks for your rating...!' }
      end
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:image,:name, :email, :message, :topic_id, { tag_ids:[] }, :rate,:user_id,:from_date,:to_date)
    end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for [@topic, @post],:html => {:class => "postsform",:multipart => true}, :remote => true  do |f| %>
            <% if @post.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@post.errors.count, "error") %> prohibited this topic from being saved:</h2>

              <ul>
                <% @post.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
              </ul>
            </div>
        <% end %>

    <div class="images">
      <%= f.label :image %><br>
      <%= f.file_field :image,class: "form-control" %>
    </div>
  <div class=namefield">
    <%= f.label :Name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :message %><br>
    <%= f.text_area :message %>
  </div>
  
  
   <div class="Tags">
	<%= f.label :Tags %><br>

		<% @tags.each do |tag| %>
			<div>
			<%= check_box_tag "post[tag_ids][]", tag.id, @post.tags.include?(tag) %>
			<%= tag.name %>
			</div>

  <% end %>	
</div>
	<%= link_to 'Create New Tags', tags_path %>
    <div class="actions">
      <div id="loading-indicator">
        <%= image_tag("\assets\images\ajax-loading.gif", :id => "loading-indicator", :style => "display:none") %>
      </div><%= f.button "Post", data: {disable_with:'<i class="fa fa-spinner fa-pulse"></i>Posting in'} ,id:"postb"%>
  </div>
<% end %>

app/views/posts/_post.html.erb
<tr>
  <td><%= post.name %></td>
  <td><%= post.user.email%></td>
  <td><%= post.message %></td>
  <td><%= post.topic.name %></td>
  <td><%if post.users.exists?(current_user)%>read<%else%>unread<%end%></td>
  <td><%=post.comments.count()%></td>
  <td><%= link_to 'Show', post  %></td>
  <td><%= link_to 'Edit', edit_post_path(post) %></td>
  <td><%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>

</tr>

app/views/posts/allposts.html.erb
<p id="notice"><%= notice %></p>
<style>
  table, th, td {
    border: 1px solid black;
    border-collapse: collapse;

  }
  th, td {
    padding: 5px;
    text-align: center;
  }
</style>
<h1>Listing Posts</h1>

<table style='width:100%'>
  <thead>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Message</th>
    <th>Topic</th>
    <th>Status</th>
    <th>No of comments</th>
    <th colspan="3">Edit_options</th>
  </tr>
  </thead>
  <tbody>

  <% @post.each do |post| %>
      <tr>
        <td><%= post.name %></td>
        <td><%= post.user.email%></td>
        <td><%= post.message %></td>
        <td><%= post.topic.name %></td>
        <td><%if post.users.exists?(current_user)%>read<%else%>unread<%end%></td>
        <td><%=post.comments.count()%></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>
<%= will_paginate @post%>
<% if @topic %>
    <%= link_to 'New Post', new_topic_post_path %> |
    <%= link_to 'Back to Topics', topic_path(@topic) %>
<% else %>
    <%= link_to 'Topics', topics_path %>
<%end%>

app/views/posts/create.js.erb
<% if @posts.errors.any? %>
alert("ERROR(S): <%= j @posts.errors.full_messages.join('; ') %>")
<%else%>
$("#posts").append('<%= j render @posts%>');
alert("Post Sucessfully created")
<%end%>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>
<script>
$(document).ajaxStart(function(){
$(".img-ajax").show();
});
$(document).ajaxStop(function(){
$(".img-ajax").hide();
});
</script>
<div class="img-ajax">
  <%=image_tag("ajax-loader.gif")%>
</div>
<h1>Listing Posts</h1>
<%if not @topic%>
<br><h3>Date Filter</h3>
<form  action="/posts" method="GET">
  From  <input type="date" name="from_date">  -
  To    <input type="date" name="to_date">
  <input type=submit value="Show Details">
</form>
    <%end%>
<br>
<% if @posts.any?%>
<table style='width:100%' id="posts">
  <thead>
    <tr>
      <th>Name</th> 
      <th>Email</th>
      <th>Message</th>
      <th>Topic</th>
      <th>Status</th>
      <th>No of<br> comments</th>
      <th colspan="3">Edit_options</th>
    </tr>
  </thead>
  <tbody>

    <%= render @posts%>

  </tbody>
</table>

<%else%>
    <strong>No posts on selected dates</strong><br>
<%end%>
<br>
<%= will_paginate @posts%>
<% if @topic %>
<%= link_to 'New Post', "#" ,id: "posts-link"%> |
    <section id ="new-posts">
<%= render 'form'%>
    </section>
<%= link_to 'Back to Topics', topic_path(@topic) %>
<% else %>
<%= link_to 'Topics', topics_path %>
<%end%>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>
<% if @topic %>
<%= link_to 'Back', topic_posts_path(@topic) %>

<%end%>

app/views/posts/show.html.erb
<script>
  $(document).ready(function() {
    <% if not @post.users.exists?(current_user.id)%>
    $.ajax({
          type: "POST",
          url: '/posts/update_post',
          data: "id=<%=@post.id%>"
        }
    )
    <%end%>
  })
</script>
<div class="posts"><p id="notice"><%= notice %></p>
<h1>
  <%= @post.name %>(<%= @post.topic.name %>)
</h1>

<section id="image">
  <h2>Image</h2>
<% if @post.image? %>
<%= image_tag @post.image.url,size:"80x80"%>
    <%end%>
</section>

  <strong>Name:</strong>
  <%= @post.name %>
  <strong>Author:</strong>
  <%= @post.user.email %>
  <strong>Message:</strong>
  <%= @post.message %>
  <strong>Topic:</strong>
  <%= @post.topic.name %>
<ul>
 <strong>Tags:</strong>
   <% @tags=@post.tags %>
  <%  @tags.each do|tag|%>
<br><%= tag.name%>
  <% end %>
  </ul>
  <strong>Previous Rating:<br></strong>
    <% (1..5).each do |ratings|%>
        <%=ratings%>-Star -> <%=@post.ratings.where(:star => ratings).count%><br>
    <%end%>
  <strong><br>Average          <%= @post.ratings.average(:star).to_f.round(2)%><br></strong>
  <%= form_for(@post,:url => postrating_path(@post)) do |f|%>
    <div id="radio_buttons">
      <% (1..5).each do |ratings|%>
      <%=radio_button_tag "rate",ratings%><%=ratings%>
      <%end%>
      <%= f.submit('rate')%>
    </div>
    <%end%>
  <br>
  <% i = @post.comments.count() %>
  <strong>  <%= link_to 'comments('+i.to_s+')' ,'#', id: "comments-link"%></strong><br>
  <section id="comments_sec">
    <section id="new_comment">
     <ol id="comments">
      <%=render @comments%>
     </ol>
<br>
  <strong>New Comment</strong>
      <%= form_for [@post,@post.comments.new], remote: true do |f| %>
          <div id="txt-field">
            <br><%= f.label :comment %>
            <br><%= f.text_area :comment ,:id =>"ct"%>
          </div>

          <div class="actions">
            <br><%= f.submit %>
          </div>
      <% end %>

      <br>
    </section>
  </section>
<br><% if @post.user_id == current_user.id%>
<%= link_to 'Edit', edit_post_path(@post) %> |<%end%>
<%= link_to 'Back', topic_posts_path(@post.topic) %>
</div>